concepts = {
    1: "CHEQUE",
    2: "COMISIONES",
    3: "IIBB",
    4: "IMPUESTOS CREDITOS",
    5: "IMPUESTOS DEBITOS",
    6: "INTERESES",
    7: "IVA",
    8: "OPERACIONES FINANCIERAS",
    9: "PERCEPCION IVA",
    10: "SELLOS",
    11: "SUELDOS",
    12: "TRANSFERENCIAS",
}