concepts = {
    "CHEQUE": 1,
    "COMISIONES": 2,
    "IIBB": 3,
    "IMPUESTOS CREDITOS": 4,
    "IMPUESTOS DEBITOS": 5,
    "INTERESES": 6,
    "IVA": 7,
    "OPERACIONES FINANCIERAS": 8,
    "PERCEPCION IVA": 9,
    "SELLOS": 10,
    "SUELDOS": 11,
    "TRANSFERENCIAS": 12,
}